<a href="https://colab.research.google.com/github/akshitasharmamca2025-jpg/Python_Assesment.py/blob/main/13_Numpy_Matrix_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# =========================
# Q13 NumPy Matrix Operations
# =========================

# 1. Create a 5x5 matrix with random integers between 1 and 10
# np.random.randint(low, high, size) generates random integers from low (inclusive) to high (exclusive).
matrix = np.random.randint(1, 11, size=(5, 5))
print("Original 5x5 Matrix:\n", matrix)
print("\n" * 2)

# 2. Calculate row-wise sum
# axis=1 specifies that the sum should be calculated across rows (for each column).
row_sum = np.sum(matrix, axis=1)
print("Row-wise Sum:", row_sum)
print("\n" * 2)

# 3. Calculate column-wise sum
# axis=0 specifies that the sum should be calculated across columns (for each row).
column_sum = np.sum(matrix, axis=0)
print("Column-wise Sum:", column_sum)
print("\n" * 2)

# 4. Calculate the transpose of the matrix
# The .T attribute or np.transpose() function can be used to get the transpose.
matrix_transpose = matrix.T
print("Transpose of the Matrix:\n", matrix_transpose)
print("\n" * 2)

# 5. Calculate the determinant of the matrix
# np.linalg.det() computes the determinant of an array.
determinant = np.linalg.det(matrix)
print("Determinant of the Matrix:", determinant)

Original 5x5 Matrix:
 [[8 9 6 5 5]
 [6 3 2 4 8]
 [8 5 9 4 9]
 [8 3 6 6 8]
 [3 4 6 9 4]]



Row-wise Sum: [33 23 35 31 26]



Column-wise Sum: [33 24 29 28 34]



Transpose of the Matrix:
 [[8 6 8 8 3]
 [9 3 5 3 4]
 [6 2 9 6 6]
 [5 4 4 6 9]
 [5 8 9 8 4]]



Determinant of the Matrix: -5404.000000000002
