<a href="https://colab.research.google.com/github/akshitasharmamca2025-jpg/Python_Assesment.py/blob/main/21_Student_marks_analysis_with_numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# =========================
# Q21 Student Marks Analysis with NumPy and Pandas
# =========================

import numpy as np
import pandas as pd

# 1. Generate a NumPy array of student marks
# Let's assume 5 students and 3 subjects (Math, Science, English)
# Marks can range from 40 to 100
num_students = 5
num_subjects = 3

# Generate random integer marks for demonstration
marks_array = np.random.randint(40, 101, size=(num_students, num_subjects))

print("NumPy Array of Student Marks:\n", marks_array)

# 2. Convert the NumPy array into a Pandas DataFrame
subject_names = ['Math', 'Science', 'English']
student_names = [f'Student_{i+1}' for i in range(num_students)]

marks_df = pd.DataFrame(marks_array, columns=subject_names, index=student_names)

print("\nPandas DataFrame of Student Marks:\n", marks_df)

# 3. Display highest marks (overall)
highest_overall_mark = marks_df.values.max()
print(f"\nHighest Mark (Overall): {highest_overall_mark}")

# 4. Display average marks (overall)
average_overall_mark = marks_df.values.mean()
print(f"Average Mark (Overall): {average_overall_mark:.2f}")

# 5. Display subject-wise statistics
print("\nSubject-wise Statistics:")
subject_stats = marks_df.describe().loc[['mean', 'max', 'min']]
print(subject_stats)

# Optionally, also display highest and average marks per student
print("\nStudent-wise Highest Marks:")
print(marks_df.max(axis=1))

print("\nStudent-wise Average Marks:")
print(marks_df.mean(axis=1))

NumPy Array of Student Marks:
 [[83 80 45]
 [66 99 71]
 [86 69 44]
 [91 56 72]
 [80 41 50]]

Pandas DataFrame of Student Marks:
            Math  Science  English
Student_1    83       80       45
Student_2    66       99       71
Student_3    86       69       44
Student_4    91       56       72
Student_5    80       41       50

Highest Mark (Overall): 99
Average Mark (Overall): 68.87

Subject-wise Statistics:
      Math  Science  English
mean  81.2     69.0     56.4
max   91.0     99.0     72.0
min   66.0     41.0     44.0

Student-wise Highest Marks:
Student_1    83
Student_2    99
Student_3    86
Student_4    91
Student_5    80
dtype: int64

Student-wise Average Marks:
Student_1    69.333333
Student_2    78.666667
Student_3    66.333333
Student_4    73.000000
Student_5    57.000000
dtype: float64
