<a href="https://colab.research.google.com/github/akshitasharmamca2025-jpg/Python_Assesment.py/blob/main/30_Numpy_program_to_create_two_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Q30. NumPy program to create two matrices and perform addition, subtraction, multiplication, and inverse operations

import numpy as np

# 1. Create two matrices
# For simplicity, let's create 3x3 matrices with random integers
# Ensure they are square and non-singular for inverse operation.

# Matrix A
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9] # This matrix is singular, let's try a different one
])

# Let's create two random matrices that are more likely to be non-singular
# for inverse operation and demonstrate operations clearly.
print("\n--- Creating Matrices ---")
np.random.seed(42) # for reproducibility
matrix1 = np.random.randint(1, 10, size=(3, 3)) # 3x3 matrix with random integers from 1 to 9
matrix2 = np.random.randint(1, 10, size=(3, 3)) # Another 3x3 matrix

print("Matrix 1 (A):\n", matrix1)
print("\nMatrix 2 (B):\n", matrix2)

# 2. Perform Addition
print("\n--- Matrix Addition (A + B) ---")
matrix_sum = matrix1 + matrix2
print(matrix_sum)

# 3. Perform Subtraction
print("\n--- Matrix Subtraction (A - B) ---")
matrix_difference = matrix1 - matrix2
print(matrix_difference)

# 4. Perform Multiplication (Element-wise and Dot Product)
print("\n--- Matrix Element-wise Multiplication (A * B) ---")
matrix_element_wise_product = matrix1 * matrix2
print(matrix_element_wise_product)

print("\n--- Matrix Dot Product (A @ B) ---")
matrix_dot_product = matrix1 @ matrix2
print(matrix_dot_product)

# 5. Perform Inverse Operation
# Check if the matrix is invertible (i.e., its determinant is not zero)
print("\n--- Matrix Inverse (A^-1 and B^-1) ---")

# Inverse of Matrix 1
determinant1 = np.linalg.det(matrix1)
print(f"Determinant of Matrix 1: {determinant1:.2f}")
if abs(determinant1) > 1e-6: # Check if determinant is close to zero
    matrix1_inverse = np.linalg.inv(matrix1)
    print("Inverse of Matrix 1:\n", matrix1_inverse)
    # Verify inverse: A * A_inv should be identity matrix
    print("Matrix 1 @ Inverse of Matrix 1 (should be Identity):\n", np.round(matrix1 @ matrix1_inverse, 2))
else:
    print("Matrix 1 is singular and does not have an inverse.")

print("\n")

# Inverse of Matrix 2
determinant2 = np.linalg.det(matrix2)
print(f"Determinant of Matrix 2: {determinant2:.2f}")
if abs(determinant2) > 1e-6: # Check if determinant is close to zero
    matrix2_inverse = np.linalg.inv(matrix2)
    print("Inverse of Matrix 2:\n", matrix2_inverse)
    # Verify inverse: B * B_inv should be identity matrix
    print("Matrix 2 @ Inverse of Matrix 2 (should be Identity):\n", np.round(matrix2 @ matrix2_inverse, 2))
else:
    print("Matrix 2 is singular and does not have an inverse.")



--- Creating Matrices ---
Matrix 1 (A):
 [[7 4 8]
 [5 7 3]
 [7 8 5]]

Matrix 2 (B):
 [[4 8 8]
 [3 6 5]
 [2 8 6]]

--- Matrix Addition (A + B) ---
[[11 12 16]
 [ 8 13  8]
 [ 9 16 11]]

--- Matrix Subtraction (A - B) ---
[[ 3 -4  0]
 [ 2  1 -2]
 [ 5  0 -1]]

--- Matrix Element-wise Multiplication (A * B) ---
[[28 32 64]
 [15 42 15]
 [14 64 30]]

--- Matrix Dot Product (A @ B) ---
[[ 56 144 124]
 [ 47 106  93]
 [ 62 144 126]]

--- Matrix Inverse (A^-1 and B^-1) ---
Determinant of Matrix 1: -11.00
Inverse of Matrix 1:
 [[-1.         -4.          4.        ]
 [ 0.36363636  1.90909091 -1.72727273]
 [ 0.81818182  2.54545455 -2.63636364]]
Matrix 1 @ Inverse of Matrix 1 (should be Identity):
 [[ 1.  0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]


Determinant of Matrix 2: 16.00
Inverse of Matrix 2:
 [[-0.25  1.   -0.5 ]
 [-0.5   0.5   0.25]
 [ 0.75 -1.   -0.  ]]
Matrix 2 @ Inverse of Matrix 2 (should be Identity):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
